### PR TITLE
Add some basic functions

### PR DESCRIPTION
**Pull request by Conni2461**
@tjdevries you should be able to test extension stuff now :)

whenever you feel like working on it. Take all the time you need. Doesn't have to happen anytime soon

### CODE REVIEW

**Comment by tjdevries** [comment]
Let me know when you switch to the other style.

**Comment by Conni2461** [comment]
That should adapt the new extension feature. But i will look into [nvim-dap-virtual-text](https://github.com/theHamsta/nvim-dap-virtual-text) on how to do cool stuff with `stackTrace` and `variables`. `dap` has some cool `custom_response_handlers` which we can use to build some cool pickers. Also i should probably rework `list_breakpoints`. Have to look at the dap source code again.
I will ping you if it is done.

**Comment by mfussenegger** [comment]
Looks interesting :)

If you need some API extensions in nvim-dap please let me know.


One thing that may be worth pointing out is that the internal `inputlist` based picker of nvim-dap is designed to be overridable.

```lua
require('dap.ui').pick_one = function(items, prompt, label_fn, cb)
  ...
end)
```

You can find a description of the functions expected behaviour [here](https://github.com/mfussenegger/nvim-fzy/blob/c3f7bfebfe43fcd034057e4f977034fd6a6435d2/doc/fzy.txt#L31)

**Comment by Conni2461** [comment]
@mfussenegger 
First of all thanks for `nvim-dap` i really really like it, even though i just started using it. And thanks for taking a look at this one.
And thanks for the insight with `pick_one` i will take a closer look at it soon.

Right now i think it would be easier for this plugin to get the `session` on demand rather than creating a response handler. Because all i am doing with that response handler is storing the session, so i can use it when the variable picker is called.

**Comment by tjdevries** [comment]
@Conni2461 you can merge whenever you want and just edit  things on master / in PRs if you want. Just ping me if you have anything you want me to look at, but I'm sure it's fine.

**Comment by Conni2461** [comment]
Had the same thought this morning. Kinda wanna get this out so people can play with it. Its only an extension :smile:
We can make it better later

**Pull request merged**
