### PR TITLE
Add support for nvim-dap >= 0.8

### LINKED ISSUE #23: Override of dap.ui.pick_one conflicts with nvim-dap 0.8.0
Hi, tks u for the plugin and it helps me a lot.

I encountered this problem after upgrading nvim-dap to 0.8.0. ⬇️
[version 0\.8\.0 with plugins telescope/telescope\-ui/nvim\-dap\-go unable to run processId at correct time\. · Issue \#1258 · mfussenegger/nvim\-dap](https://github.com/mfussenegger/nvim-dap/issues/1258)

Is there any plan to resolve this conflict, or how can I make this plugin work with the latest nvim-dap?

### PR DESCRIPTION
**Pull request by cryptomilk**
Fixes #23

### CODE REVIEW

**Comment by cryptomilk** [comment]
This might be the wrong way to fix it. The pick_one function uses vim.ui.select() which can be replaced. This is done by:

https://github.com/nvim-telescope/telescope-ui-select.nvim

**Comment by gcalmettes** [comment]
Confirming that this works perfectly. 
Thanks @cryptomilk

**Comment by cryptomilk** [comment]
Ping

**Comment by cryptomilk** [comment]
@Conni2461 @theHamsta @zoriya @JRasmusBm

**Comment by gierdo** [comment]
Ping, as well :)

I solved it like this for me until this has been merged:

```
      local dap_ui = require("dap.ui")
      local original_pick_one = dap_ui.pick_one
      telescope.load_extension("dap")
      dap_ui.pick_one = original_pick_one
```

**Comment by Conni2461** [comment]
Thanks :)

**Pull request merged**
